Feat calc field radia model
lnls-fac/fieldmaptrack pull request #16
Opened 2022-12-13 20:56 UTC by Gabrielrezende-asc

This update makes it possible to calculate the RK trajectory in an ID using the ID's Radia model. The function calc_field returns the field in an input point, if a Radia model is given, then the field will be calculated using this model, otherwise, the field will be calculated using an interpolation over the field map.

2022-12-16 11:39 UTC, fernandohds564 requested changes

2022-12-16 11:39 UTC, fernandohds564 commented on fieldmaptrack/track.py
> +        else:
In order to decrease identation level, consider doing this:
```python3
        if self.radia_model is not None:
            return self.radia_model.get_field_at_point([rx, ry, rz])
        
        try:
            return self.fieldmap.interpolate(rx, ry, rz)
        except (fieldmap.OutOfRangeRangeRx, 
                fieldmap.OutOfRangeRxMin,
                fieldmap.OutOfRangeRy):
            rstr = 'extrapolation at ' + str((rx, ry, rz))
            if self.not_raise_range_exceptions:
                print(rstr)
                return 0.0, 0.0, 0.0
            raise TrackException(rstr)
        except fieldmap.OutOfRangeRz:
            return 0.0, 0.0, 0.0
```

this approach makes the code shorter, cleaner and easy to read.

2022-12-16 11:41 UTC, fernandohds564 commented on fieldmaptrack/track.py
> +        """."""
you could add a docstring here to make it clear the order of the components that will be returned.

2022-12-16 12:11 UTC, fernandohds564 approved these changes

2022-12-16 14:46 UTC, xresende approved these changes

2022-12-16 15:10 UTC, murilobalves approved these changes

2023-01-04 12:39 UTC, vellosok75 approved these changes

2023-01-04 13:06 UTC, merged